on: [push, pull_request]

name: Integration testing

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [stable, nightly]
    services:
      redis:
        image: docker.io/redis/redis-stack
        ports:
          - 6379:6379
    name: Test examples with ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.version }}
      - run: cargo test --examples
