on: [push, pull_request]

name: Integration testing

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        version: [stable, nightly]
    services:
      redis:
        image: docker.io/redis/redis-stack
        ports:
          - 6379:6379
    name: Test examples with ${{ matrix.version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.version }}
          override: true
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --examples
