on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        version: [stable, nightly]
    name: Check and test on ${{ matrix.os }} with ${{ matrix.version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: minimal
          toolchain: ${{ matrix.version }}
          components: clippy
      - run: cargo check
      - run: cargo clippy -- -D warnings
      - run: cargo test
